### ISSUE TITLE
shpotify opens spotify rather than displaying status

### ISSUE THREAD

**Issue by Luticus** [hnarayanan/shpotify#118]
I have an odd issue on a mac where when I run spotify status in the CLI it will open or switch to the spotify GUI rather than displaying the status of the currently playing song.  This just started recently.  I'm unsure what changed to cause it.  This breaks wrapper scripts I've created which rely on this functionality.

**Comment by dmofot** [comment]
Can you give a little more information, like version of OSX and version of Spotify?

If you issue a `spotify status` without having Spotify open, it will open Spotify in order to get the status.  For me (Mojave 10.14.5 and Spotify 1.1.10.540.gfcf0430f), if Spotify is minimized to the dock, it doesn't switch back to the GUI.

**Comment by Luticus** [comment]
I'm on Spotify 1.1.10.540

My mac is at:  10.14.5

Mine will switch back to the GUI even if the app is open and non minimized.  
...And nevermind.  Apparently I just needed to reboot the box.  I'm not sure why that was the case, but it was.  Well if you get this question again, let people know to try the good ol' windows fix.  :)
